name: ci

on: push

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Cloning Repo
      run: git clone --depth=1 https://github.com/radareorg/sdb
    - name: Windows Dependencies
      run: |
        pip install meson ninja
    - name: Building Sdb
      run: cd sdb && meson build && ninja -C build
    - name: Pub
      uses: actions/upload-artifact@v2-preview
      uses: actions/upload-artifact@v2
      with:
        path: sdb/src/*.exe
    - name: Rls
      - run: |
         upload_url=$(curl -sL https://api.github.com/repos/actions/checkout/releases/latest | jq -r '.upload_url')
         echo ::set-env name=UPLOAD_URL::$upload_url
        shell: bash
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Cloning Repo
      run: git clone --depth=1 https://github.com/radareorg/sdb
    - name: Building Sdb
      run: cd sdb && make -j4 && cd ..
    - name: Packaging
      run: cd sdb/dist/debian && make -j4 && cd ../../..
    - name: Running tests
      run: cd sdb && make test && cd ..
    - name: Pub
      uses: actions/upload-artifact@v2
      with:
        path: sdb/dist/debian/*.deb
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Cloning Repo
      run: git clone --depth=1 https://github.com/radareorg/sdb
    - name: Building Sdb
      run: cd sdb && make -j4 && cd ..
    - name: Packaging
      run: cd sdb/dist/macos && make -j4 && cd ../../..
    - name: Running tests
      run: cd sdb && make test && cd ..
    - name: Pub
      uses: actions/upload-artifact@v2
      with:
        path: sdb/dist/macos/*.pkg
